============================================================
Hack The Box Kitty Theme
============================================================
font_family JetBrains Mono
font_size 15
------------------------------------------------------------
Background / foreground
------------------------------------------------------------
background #1a2332
foreground #a4b1cd

background_opacity 0.92

cursor #9fef00
cursor_text_color #1a2332

selection_background #313f55
selection_foreground #ffffff

url_color #5cb2ff

------------------------------------------------------------
HTB ANSI palette
------------------------------------------------------------
Black
color0 #000000
color8 #666666

Red
color1 #ff3e3e
color9 #ff8484

Green
color2 #9fef00
color10 #c5f467

Yellow
color3 #ffaf00
color11 #ffcc5c

Blue
color4 #004cff
color12 #5cb2ff

Purple
color5 #9f00ff
color13 #c16cfa

Cyan
color6 #2ee7b6
color14 #5cecc6

White
color7 #ffffff
color15 #ffffff

------------------------------------------------------------
Window
------------------------------------------------------------
window_padding_width 10
hide_window_decorations yes

------------------------------------------------------------
Cursor
------------------------------------------------------------
cursor_shape block
cursor_blink_interval 0.6
cursor_stop_blinking_after 15.0

------------------------------------------------------------
Tabs
------------------------------------------------------------
tab_bar_edge top
tab_bar_style powerline

active_tab_foreground #1a2332
active_tab_background #9fef00

inactive_tab_foreground #a4b1cd
inactive_tab_background #141d2b

tab_bar_background #141d2b

------------------------------------------------------------
General
------------------------------------------------------------
shell_integration enabled
enable_audio_bell no
visual_bell_duration 0
scrollback_lines 100000

Don't ask before closing
confirm_os_window_close 0
enabled_layouts splits

# Create splits
map ctrl+shift+o launch --location=vsplit
map ctrl+shift+e launch --location=hsplit

# Navigate between splits
map ctrl+shift+left neighboring_window left
map ctrl+shift+right neighboring_window right
map ctrl+shift+up neighboring_window up
map ctrl+shift+down neighboring_window down

# Resize the current split
#map ctrl+shift+left resize_window narrower
#map ctrl+shift+right resize_window wider
#map ctrl+shift+up resize_window shorter
#map ctrl+shift+down resize_window taller

map ctrl+h neighboring_window left
map ctrl+l neighboring_window right
map ctrl+k neighboring_window up
map ctrl+j neighboring_window down

map ctrl+shift+h move_window left
map ctrl+shift+l move_window right
map ctrl+shift+k move_window up
map ctrl+shift+j move_window down
map ctrl+shift+space layout_action maximize
